### Local Orchestration Start
@licensePlate = ABC-111
POST http://localhost:7071/api/orchestration/ParkingOrchestration
Content-Type: application/json

"{{licensePlate}}"

### Local Get Status
@instance = 12969c2a9a50411e9c5dbc1efcdc1d45
@code = 3bpVhOisFoBLgaw62vAJFbd2l2ubpqPZKiAgwzzUcBxf9r2fs1baxA==
GET http://localhost:7071/runtime/webhooks/DurableTaskExtension/instances/{{instance}}
    ?taskHub=DurableFunctionsHub&connection=Storage
    &code={{code}}
