### Local Orchestration Start
@licensePlate = XYZ-999
POST http://localhost:7071/api/orchestration/ParkingOrchestration
Content-Type: application/json

"{{licensePlate}}"

### Local Get Status
@instance = f1205f2db6994994bacd5e20239019ce
@code = 3bpVhOisFoBLgaw62vAJFbd2l2ubpqPZKiAgwzzUcBxf9r2fs1baxA==
GET http://localhost:7071/runtime/webhooks/DurableTaskExtension/instances/{{instance}}
    ?taskHub=DurableFunctionsHub&connection=Storage
    &code={{code}}
