### Local Orchestration Start
@licensePlate = ABC-111
POST http://localhost:7071/api/orchestration/ParkingOrchestration
Content-Type: application/json

"{{licensePlate}}"

### Local Get Status
@instance = ecddcbd2174c433bbdcc71f1c28dae48
@code = 3bpVhOisFoBLgaw62vAJFbd2l2ubpqPZKiAgwzzUcBxf9r2fs1baxA==
GET http://localhost:7071/runtime/webhooks/DurableTaskExtension/instances/{{instance}}
    ?taskHub=DurableFunctionsHub&connection=Storage
    &code={{code}}
